### ISSUE TITLE
'timeout' issue on Raspberry Pi model A+ (armv6l)

### ISSUE THREAD

**Issue by RogueM** [parallaxinc/PropellerManager#2]
I though t I would report my experience after trying the latest propman (as in master branch, not one of the release). I experienced the same with propman 0.1.1 however, minus some of the messages received even upon successful uploads.

on first attempt, I always receive the following:

Connecting to 'ttyAMA0'... Failed to write value!
Failed to write value!
ERROR: 9
[ ERROR 9 ]: Device unexpectedly disconnected!
[ NOT FOUND ]

second try (if within about 5 sec):

Connecting to 'ttyAMA0'... Failed to write value!
Failed to write value!
[ DONE ]
Downloading to RAM... [ DONE ]
Verifying RAM... [ DONE ]

my code works at that point, so all is good from that end, but I ALWAYS receive those ERROR 9 messages ona first attempt, and have to (relatively) rapidly retry.

This version (-v states CLI 0.0.0 incidentally, as noted on front page) also presents me with the 'Connecting to 'ttyAMA0'... Failed to write value!' message, regardless of success or failure, where as 0.1.1 didn't.

Let me know if you need additional info. I would add that I am using a custom pin to upload to a Pimoroni Propeller HAT.

**Comment by bweir** [comment]
This should be resolved in the latest version of PropellerIDE. Let me know what you experience.
