### ISSUE TITLE
'Failed to write value!' failure to assert Raspberry Pi GPIO reset on Raspbian Jessie

### ISSUE THREAD

**Issue by Gadgetoid** [parallaxinc/PropellerManager#3]
I've built and installed the latest Propeller IDE form source on Raspbian Jessie, and seem to have some trouble with downloading code to Propeller HAT which requires a GPIO reset asserted on Pin 17.

The /sys/class GPIO is accessible to userspace on the Pi, however it will not work in `propman` until I manually `echo 17 > /sys/class/gpio/export`, at which point it will upload successfully. I have to do this before each and every upload attempt, however, so it's clearly successfully unexporting!

Without the manual export, the errors generated are:

``` text
Using GPIO pin 17 for hardware reset
Failed to write value!
Failed to open gpio direction for writing!
Failed to open gpio value for writing!
Failed to open gpio value for writing!
Failed to write value!
[PropellerManager] ttyAMA0: Downloading image (56 bytes, 341 ms)
[PropellerManager] ttyAMA0: ERROR: Device not found
```

The last error is exactly what I'd expect if no GPIO reset were successful.

This is on Raspbian Jessie, 4.1.7-v7+ #817.

**Comment by bweir** [comment]
Ahhh yeah I've been seeing this myself. Now that my RPi build environment
is set up, it'll be much faster to troubleshoot. I'll probably look at this
today.

**Comment by bweir** [comment]
I spent a good hour and a half trying to figure out what the deal is here. I tried exporting via Qt libraries, C++ standard libraries, the regular C implementation, nothing works.

At this point, I can definitely say it's not a problem with how it's implemented in the IDE. It seems like it's a permissions issue in Jessie, but I'm really not sure where to start in troubleshooting it. Even calling the "gpio" command using the system() command fails, but the exact same command through bash succeeds.

It doesn't make any sense!

**Comment by Gadgetoid** [comment]
That's bizarre, since it's clearly capable of writing to, and unexporting a GPIO pin when it's set up manually beforehand. I'll delve into the code and see if I can find anything.

**Comment by Gadgetoid** [comment]
I think the problem is the speed at which you're doing things. I suspect the file system GPIO access is slow enough that you're attempting to write to "direction" or "value" before they've even been created.

After some tinkering in C, the only way I could reliably turn an LED on and off was this:

``` c
#include <stdio.h>
#include <string.h>
#include <fcntl.h>

int main(){
  int fd;

  printf("Exporting\n");
  fd = open("/sys/class/gpio/export", O_WRONLY);
  write(fd, "17", 2);
  close(fd);

  sleep(1);

  printf("Setting Direction\n");
  fd = open("/sys/class/gpio/gpio17/direction", O_WRONLY);
  write(fd, "out", 3);
  close(fd);

  sleep(1);

  printf("Writing 1\n");
  fd = open("/sys/class/gpio/gpio17/value", O_WRONLY);
  write(fd, "1", 1);

  sleep(1);

  printf("Writing 0\n");
  write(fd, "0", 1);
  close(fd);

  sleep(1);

  printf("Unexporting\n");
  fd = open("/sys/class/gpio/unexport", O_WRONLY);
  write(fd, "17", 2);
  close(fd);
}
```

I'm sure my delays are generously large, but compiling this code resulted in a binary which would repeatedly do exactly what you might expect- turn the LED I'd attached to GPIO 17 on and then off.

**Comment by bweir** [comment]
HAH. That's genius. I added a 100ms sleep to immediately after it writes to 'export', and that seems to do the trick. Try for yourself! It's kind of hilarious.

I guess we found one problem with having an operating system where everything is a file.

**Comment by Gadgetoid** [comment]
Yup, can confirm it's fixed by 5f5157ceb5deabbd7dafde25bced013605d501b5

Now I'm seeing this

``` text
[PropellerManager] ttyAMA0: ERROR: Download timed out after 343 ms
[PropellerManager] ttyAMA0: ERROR: Verify RAM Failed
```

However, a basic test in which I change the LED that is blinking by changing the pin constant before each upload shows that the uploads are actually successful.

**Comment by bweir** [comment]
Yeah, there still seems to be some weirdness with timeouts. Large downloads are lasting forever for some reason too.

Nothing behaves the same way on the Pi because it isn't reliable with timing. >.>

Can you send me the application you're using to test? I'd like to add test Spin code for Raspberry Pi.

To that end, is there anything I can blink on the Propeller HAT that doesn't require me to wire anything to the breadboard? I already have the thing sealed in its case. <.<

**Comment by Gadgetoid** [comment]
There's no blink LED on Propeller HAT unfortunately. I use some robust little green LEDs that I can get away with using no resistors for.

Currently I'm just using a really quick and dirty blink script that looks something like this:

``` spin
CON
  _CLKMODE = xtal1 + pll16x
  _XINFREQ = 6_000_000

  MY_LED_PIN = 0

PUB main
  DIRA[MY_LED_PIN] := 1

  repeat
    OUTA[MY_LED_PIN] := 1
    waitcnt(cnt + clkfreq)
    OUTA[MY_LED_PIN] := 0
    waitcnt(cnt + clkfreq)
```
